x=input("enter the first number: ")
y=input("enter the second number: ")
result1 = float(x) + float(y)
result2 = float(x) - float(y)
result3 = float(x) / float(y)
result4 = float(x) * float(y)
result5 = pow(float(x), float(y))
print("sum = ", result1)
print("product =", result4)
print("division =", result3)
print("subtraction =", result2)
print(x,"raised to the power" , y, "is" , result5)
